[package]

name = "scan_obj"
version = "0.5.0"
authors = ["Daniel Keep <daniel.keep@gmail.com>"]

[dependencies.scan]

git = "https://github.com/DanielKeep/rust-scan.git"

[dependencies.scan_util]

git = "https://github.com/DanielKeep/rust-scan-util.git"
